kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/oliver006/drone-cloud-run

steps:
  - name: tests
    image: "golang:1.16"
    environment:
      COVERALLS_TOKEN:
        from_secret: coveralls-token
    commands:
      - 'echo " ! gofmt -d *.go 2>&1 | read " | bash'
      - 'go vet ./...'
      - "go build"
      - "go test -v -covermode=atomic -cover -race -coverprofile=coverage.txt"
      - "go get github.com/mattn/goveralls"
      - "/go/bin/goveralls -v -coverprofile=coverage.txt -service=drone.io"
    when:
      event:
        - push
        - pull_request


  - name: test-docker-build
    image: plugins/docker
    settings:
      repo: oliver006/drone-cloud-run
      tags: "latest"
      debug: true
      dry_run: true
      build_args:
        - 'TAG=test'
        - 'SHA1=${DRONE_COMMIT_SHA}'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - pull_request


  - name: lint
    image: golangci/golangci-lint:latest-alpine
    pull: always
    commands:
      - apk add --update make
      - golangci-lint run --tests=false --exclude-use-default
      - golangci-lint run -D=errcheck   --exclude-use-default
    when:
      event:
        - pull_request
        - push
        - tag


  - name: update-dummy-docker-tst-image
    image: plugins/docker
    settings:
      username: _json_key
      password:
        from_secret: google_credentials
      repo: gcr.io/phone-21zoo-com/drone-cloud-run-test
      registry: gcr.io
      tags: latest
      dockerfile: tst/Dockerfile
    when:
      branch:
        - master
      event:
        - push


  - name: build-and-publish-new-drone-image-for-test
    image: plugins/docker
    settings:
      repo: oliver006/drone-cloud-run
      tags: test
      debug: true
      build_args:
        - 'TAG=test'
        - 'SHA1=${DRONE_COMMIT_SHA}'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push


  - name: sleep-10s
    image: alpine
    commands:
      - sleep 10
    when:
      branch:
        - master
      event:
        - push


  - name: deploy-using-new-test-drone-image
    image: oliver006/drone-cloud-run:test
    pull: always
    settings:
      action: deploy
      service: test-drone-cloud-run-master
      image: gcr.io/phone-21zoo-com/drone-cloud-run-test:latest
      memory: 128Mi
      region: us-central1
      allow_unauthenticated: true
      environment:
        VAR_1: "var01"
        VERSION: "${DRONE_COMMIT_SHA}"
      token:
        from_secret: google_credentials
    when:
      branch:
        - master
      event:
        - push


  - name: on-tag-build-and-publish-new-drone-image
    image: plugins/docker
    settings:
      repo: oliver006/drone-cloud-run
      tags: "latest,${DRONE_TAG}"
      debug: true
      build_args:
        - 'TAG=${DRONE_TAG}'
        - 'SHA1=${DRONE_COMMIT_SHA}'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
